version: '3'
services:
  postgres-dev:
    image: postgres
    restart: always
    environment:
      - POSTGRESS_USER=LocalDev
      - POSTGRES_PASSWORD=tempForLocalDevelopment
    ports:
      - '5438:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/blocks.sql:/docker-entrypoint-initdb.d/create_tables.sql
